version: '3'
services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      
# REF: https://herewecode.io/blog/create-a-postgresql-database-using-docker-compose/